# Responsable : FOGAING Franck-Noel
services:
  ecosort:
    build: .
    container_name: ecosort_container
    ports:
      - "8501:8501"
    restart: unless-stopped
    mem_limit: 3g
    mem_reservation: 1g